[project]
name = "agenticgraphrag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12,<3.14"
dependencies = [
    "chromadb>=1.5.9",
    "ollama>=0.6.3",
    "pandas>=3.0.6",
    "pydantic>=2.13.5",
    "pytest>=9.1.1",
    "python-dotenv>=1.2.4",
    "pytigergraph>=2.0.4",
    "requests>=2.34.2",
    "ruff>=0.16.10",
    "sentence-transformers>=6.1.0",
]

[project.scripts]
agenticgraphrag = "agenticgraphrag:main"

[build-system]
requires = ["uv_build>=0.12.22,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ipykernel>=7.4.0",
    "jupyter>=1.1.1",
]
